import Footer from "@/components/Shared/Footer/Footer";
import Navbar from "@/components/Shared/Navbar/Navbar";
import NavbarWrapper from "@/components/Shared/Navbar/NavbarWrapper";
import ScrollNavbar from "@/components/Shared/Navbar/ScrollNavbar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Pet Adoption HomePage",
  description: "Generated by create next app",
};

const CommonLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <ScrollNavbar>
        <NavbarWrapper />
      </ScrollNavbar>
      <div className="min-h-screen">{children}</div>
      <Footer />
    </>
  );
};

export default CommonLayout;